#define PIN_VOLTAGE ADC1_CHANNEL_0
#define PIN_CURRENT ADC1_CHANNEL_0

#define PIN_RESISTANCE ADC1_CHANNEL_1
#define PIN_CAPASITANCE ADC1_CHANNEL_1

#define PIN_INDUCTANCE ADC1_CHANNEL_1
#define PIN_SIGNAL_GENERATOR ADC1_CHANNEL_2

#define PIN_OSC_CH1 ADC1_CHANNEL_3
#define PIN_OSC_CH2 ADC1_CHANNEL_4

#define RESOLUCION_ADC 4095
#define VOLTAJE_REFERENCIA 3.3